language: node_js

node_js:
  - 0.6
  - 0.8
  - 0.9

notifications:
  email:
    recipients:
      - jmillan@aliax.net
      - ibc@aliax.net
      - saghul@gmail.com
    on_success: change
    on_failure: always
